
//The following lines are for symbols and emojis. This is necessary in order to make the cursor not flip out since the symbols and emojis mess around with the editor. To use them just call their simple display function {NAMEOFCONST}

// Group Buildings

CONST  EMOTE_HOUSE_BUILDING  =                "🏠"
CONST  EMOTE_JAPANESE_CASTLE  =               "🏯"
CONST  EMOTE_EUROPEAN_CASTLE  =               "🏰"
CONST  EMOTE_HINDU_TEMPLE  =                  "🛕"
CONST  EMOTE_HOTEL   =                        "🏨"
CONST  EMOTE_LOVE_HOTEL   =                   "🏩"
CONST  EMOTE_HOSPITAL   =                     "🏥"
CONST  EMOTE_BANK   =                         "🏦"
CONST  EMOTE_SCHOOL   =                       "🏫"
CONST  EMOTE_OFFICE_BUILDING   =              "🏢"
CONST  EMOTE_ARENA   =                        "🏟️"
CONST  EMOTE_EUROPEAN_POST_OFFICE   =         "🏤"
CONST  EMOTE_HOUSE_BUILDINGS   =              "🏘️"
CONST  EMOTE_DERELICT_HOUSE_BUILDING   =      "🏚️"
CONST  EMOTE_CLASSICAL_BUILDING   =           "🏛️"
CONST  EMOTE_HOUSE_WITH_GARDEN   =            "🏡"
CONST  EMOTE_BUILDING_CONSTRUCTION   =        "🏗️"
CONST  EMOTE_CHURCH   =                       "⛪"
CONST  EMOTE_SHINTO_SHRINE   =                "⛩️"
CONST  EMOTE_MOSQUE   =                       "🕌"
CONST  EMOTE_SYNAGOGUE   =                    "🕍"
CONST  EMOTE_KAABA   =                        "🕋"
CONST  EMOTE_CIRCUS_TENT   =                  "🎪"
CONST  EMOTE_CITYSCAPE   =                    "🌆"
CONST  EMOTE_BRIDGE_AT_NIGHT   =              "🌉"

// Group Items

CONST  EMOTE_KEY  =                           "🔑"
CONST  EMOTE_AXE  =                           "🪓"
CONST  EMOTE_COMPASS  =                       "🧭"
CONST  EMOTE_BONE  =                          "🦴"
CONST  EMOTE_TOOTH  =                         "🦷"
CONST  EMOTE_OLD_KEY  =                       "🗝️"
CONST  EMOTE_DAGGER_KNIFE  =                  "🗡️"
CONST  EMOTE_SPOON   =                        "🥄"
CONST  EMOTE_WILTED_FLOWER   =                "🥀"
CONST  EMOTE_BOUQUET   =                      "💐"
CONST  EMOTE_CLOSED_UMBRELLA   =              "🌂"
CONST  EMOTE_RECEIPT   =                      "🧾"
CONST  EMOTE_RIBBON   =                       "🎀"
CONST  EMOTE_CANDLE   =                       "🕯️"
CONST  EMOTE_ELECTRIC_TORCH   =               "🔦"
CONST  EMOTE_ARTIST_PALETTE   =               "🎨"
CONST  EMOTE_BOMB   =                         "💣"
CONST  EMOTE_FIRECRACKER   =                  "🧨"
CONST  EMOTE_BALLOON   =                      "🎈"
CONST  EMOTE_TICKET   =                       "🎫"
CONST  EMOTE_ADMISSION_TICKETS   =            "🎟️"
CONST  EMOTE_ROLL_OF_PAPER   =                "🧻"
CONST  EMOTE_BAR_OF_SOAP   =                  "🧼"
CONST  EMOTE_SPONGE   =                       "🧽"
CONST  EMOTE_RAZOR   =                        "🪒"
CONST  EMOTE_TEST_TUBE   =                    "🧪"
CONST  EMOTE_PETRI_DISH   =                   "🧫"
CONST  EMOTE_MAGNET   =                       "🧲"
CONST  EMOTE_NUT_AND_BOLT   =                 "🔩"
CONST  EMOTE_WRENCH   =                       "🔧"
CONST  EMOTE_HAMMER   =                       "🔨"
CONST  EMOTE_PICK   =                         "⛏️"
CONST  EMOTE_CHAINS   =                       "⛓️"
CONST  EMOTE_GEAR   =                         "⚙️"
CONST  EMOTE_TEDDY_BEAR   =                   "🧸"
CONST  EMOTE_JAPANESE_DOLLS   =               "🎎"
CONST  EMOTE_PRAYER_BEADS   =                 "📿"
CONST  EMOTE_RED_GIFT_ENVELOPE   =            "🧧"
CONST  EMOTE_JIGSAW_PUZZLE_PIECE   =          "🧩"
CONST  EMOTE_SPOOL_OF_THREAD   =              "🧵"
CONST  EMOTE_BALL_OF_YARN   =                 "🧶"
CONST  EMOTE_SAFETY_PIN   =                   "🧷"
CONST  EMOTE_YO_YO   =                        "🪀"
CONST  EMOTE_KITE   =                         "🪁"
CONST  EMOTE_PARACHUTE   =                    "🪂"
CONST  EMOTE_CAMERA   =                       "📷"
CONST  EMOTE_CAMERA_WITH_FLASH   =            "📸"
CONST  EMOTE_VIDEO_CAMERA   =                 "📹"
CONST  EMOTE_VIDEOCASSETTE   =                "📼"
CONST  EMOTE_HEADPHONE   =                    "🎧"
CONST  EMOTE_DVD   =                          "📀"
CONST  EMOTE_OPTICAL_DISC   =                 "💿"
CONST  EMOTE_FILE_FOLDER   =                  "📁"
CONST  EMOTE_FLOPPY_DISK   =                  "💾"
CONST  EMOTE_CONTROLLER   =                   "🎮"
CONST  EMOTE_LEFT_MAGNIFYING_GLASS   =        "🔍"
CONST  EMOTE_RIGHT_MAGNIFYING_GLASS   =       "🔎"
CONST  EMOTE_CIGARETTE   =                    "🚬"
CONST  EMOTE_SPIRAL_SHELL   =                 "🐚"
CONST  EMOTE_LIPSTICK   =                     "💄"
CONST  EMOTE_CLAPPER_BOARD  =                 "🎬"

// Group Food

CONST  EMOTE_POTATO  =                        "🥔"
CONST  EMOTE_CARROT  =                        "🥕"
CONST  EMOTE_BAGUETTE_BREAD  =                "🥖"
CONST  EMOTE_EGG  =                           "🥚"
CONST  EMOTE_PRETZEL  =                       "🥨"
CONST  EMOTE_CUT_OF_MEAT  =                   "🥩"
CONST  EMOTE_CHEESE_WEDGE  =                  "🧀"
CONST  EMOTE_BREAD   =                        "🍞"
CONST  EMOTE_BUTTER   =                       "🧈"
CONST  EMOTE_MEAT_ON_BONE   =                 "🍖"
CONST  EMOTE_POULTRY_LEG   =                  "🍗"
CONST  EMOTE_HONEY_POT   =                    "🍯"
CONST  EMOTE_ICE_CREAM   =                    "🍨"
CONST  EMOTE_CHOCOLATE_BAR   =                "🍫"
CONST  EMOTE_PEANUTS   =                      "🥜"
CONST  EMOTE_COOKIE   =                       "🍪"
CONST  EMOTE_CANDY   =                        "🍬"
CONST  EMOTE_BIRTHDAY_CAKE   =                "🎂"

// Group Fruits

CONST  EMOTE_GRAPES   =                       "🍇"
CONST  EMOTE_PEACH   =                        "🍑"
CONST  EMOTE_CHERRIES   =                     "🍒"
CONST  EMOTE_STRAWBERRY   =                   "🍓"
CONST  EMOTE_KIWIFRUIT   =                    "🥝"
CONST  EMOTE_WATERMELON   =                   "🍉"
CONST  EMOTE_TANGERINE   =                    "🍊"
CONST  EMOTE_LEMON   =                        "🍋"
CONST  EMOTE_BANANA   =                       "🍌"
CONST  EMOTE_PINEAPPLE   =                    "🍍"
CONST  EMOTE_RED_APPLE   =                    "🍎"
CONST  EMOTE_GREEN_APPLE   =                  "🍏"
CONST  EMOTE_PEAR   =                         "🍐"
CONST  EMOTE_COCONUT   =                      "🥥"

// Group Veggies

CONST  EMOTE_LEAFY_GREEN   =                  "🥬"
CONST  EMOTE_BROCCOLI   =                     "🥦"
CONST  EMOTE_TOMATO   =                       "🍅"
CONST  EMOTE_GARLIC   =                       "🧄"
CONST  EMOTE_ONION   =                        "🧅"
CONST  EMOTE_MUSHROOM   =                     "🍄"

// Group Drink

CONST  EMOTE_WINE_GLASS  =                    "🍷"
CONST  EMOTE_BEER_MUG  =                      "🍺"
CONST  EMOTE_CLINKING_BEER_MUGS   =           "🍻"
CONST  EMOTE_TROPICAL_DRINK   =               "🍹"
CONST  EMOTE_COCKTAIL_GLASS   =               "🍸"
CONST  EMOTE_CLINKING_GLASSES   =             "🥂"
CONST  EMOTE_TUMBLER_GLASS   =                "🥃"
CONST  EMOTE_BOTTLE_WITH_POPPING_CORK   =     "🍾"
CONST  EMOTE_GLASS_OF_MILK   =                "🥛"

// Group Victory Items

CONST  EMOTE_FIRST_PLACE_MEDAL  =             "🥇"
CONST  EMOTE_SECOND_PLACE_MEDAL  =            "🥈"
CONST  EMOTE_THIRD_PLACE_MEDAL  =             "🥉"
CONST  EMOTE_TROPHY  =                        "🏆"

// Group Special Treasures

CONST  EMOTE_CROWN  =                         "👑"
CONST  EMOTE_RING  =                          "💍"
CONST  EMOTE_GEM_STONE  =                     "💎"
CONST  EMOTE_AMPHORA   =                      "🏺"
CONST  EMOTE_SCROLL   =                       "📜"

// Group Heart Symbols Status

CONST  EMOTE_TWO_HEARTS   =                   "💕"
CONST  EMOTE_SPARKLING_HEART   =              "💖"
CONST  EMOTE_HEART_WITH_ARROW   =             "💘"
CONST  EMOTE_HEART_WITH_RIBBON   =            "💝"
CONST  EMOTE_REVOLVING_HEARTS   =             "💞"
CONST  EMOTE_HEART_DECORATION   =             "💟"
CONST  EMOTE_BROKEN_HEART  =                  "💔"
CONST  EMOTE_GROWING_HEART  =                 "💗"
CONST  EMOTE_BLACK_HEART   =                  "🖤"
CONST  EMOTE_BROWN_HEART   =                  "🤎"
CONST  EMOTE_WHITE_HEART   =                  "🤍"
CONST  EMOTE_PURPLE_HEART   =                 "💜"
CONST  EMOTE_BLUE_HEART   =                   "💙"
CONST  EMOTE_GREEN_HEART   =                  "💚"
CONST  EMOTE_YELLOW_HEART   =                 "💛"
CONST  EMOTE_ORANGE_HEART   =                 "🧡"

// Group Status Symbols

CONST  EMOTE_ANGER_SYMBOL  =                  "💢"
CONST  EMOTE_COLLISION_SYMBOL  =              "💥"
CONST  EMOTE_DROP_OF_BLOOD  =                 "🩸"
CONST  EMOTE_DIZZY_SYMBOL   =                 "💫"
CONST  EMOTE_SLEEPING_SYMBOL   =              "💤"
CONST  EMOTE_DASH_SYMBOL   =                  "💨"
CONST  EMOTE_HUNDRED_POINTS_SYMBOL   =        "💯"
CONST  EMOTE_SKULL   =                        "💀"
CONST  EMOTE_BRAIN   =                        "🧠"

// Group Senses & Body

CONST  EMOTE_EYE   =                          "👁️"
CONST  EMOTE_NOSE   =                         "👃"
CONST  EMOTE_TONGUE   =                       "👅"
CONST  EMOTE_EYES  =                          "👀"
CONST  EMOTE_EAR  =                           "👂"
CONST  EMOTE_FOOT   =                         "🦶"
CONST  EMOTE_LEG   =                          "🦵"

// Group Landscapes

CONST  EMOTE_MOUNT_FUJI  =                    "🗻"
CONST  EMOTE_NIGHT_WITH_STARS   =             "🌃"
CONST  EMOTE_SUNRISE_OVER_MOUNTAINS   =       "🌄"
CONST  EMOTE_SUNRISE   =                      "🌅"
CONST  EMOTE_CITYSCAPE_AT_DUSK   =            "🌆"
CONST  EMOTE_SUNSET_OVER_BUILDINGS   =        "🌇"
CONST  EMOTE_WATER_WAVE   =                   "🌊"
CONST  EMOTE_DESERT_ISLAND   =                "🏝️"
CONST  EMOTE_DESERT   =                       "🏜️"
CONST  EMOTE_NATIONAL_PARK   =                "🏞️"
CONST  EMOTE_MOUNTAIN   =                     "⛰️"
CONST  EMOTE_SNOW_CAPPED_MOUNTAIN   =         "🏔️"
CONST  EMOTE_VOLCANO   =                      "🌋"
CONST  EMOTE_HOLE   =                         "🕳️"

// Group Chance Symbols

CONST  EMOTE_FOUR_LEAF_CLOVER  =              "🍀"
CONST  EMOTE_GAME_DIE  =                      "🎲"
CONST  EMOTE_SLOT_MACHINE  =                  "🎰"

// Group Objects

CONST  EMOTE_IZAKAYA_LANTERN  =               "🏮"
CONST  EMOTE_DOOR  =                          "🚪"
CONST  EMOTE_TOILET  =                        "🚽"
CONST  EMOTE_BATHTUB  =                       "🛁"
CONST  EMOTE_SLED  =                          "🛷"
CONST  EMOTE_SPOOL_OF_THREAD  =               "🧵"
CONST  EMOTE_CHAIR  =                         "🪑"
CONST  EMOTE_SALT_SHAKER  =                   "🧂"
CONST  EMOTE_CRYSTAL_BALL   =                 "🔮"
CONST  EMOTE_SPIDER_WEB   =                   "🕸️"
CONST  EMOTE_WIND_CHIME   =                   "🎐"
CONST  EMOTE_FOUNTAIN   =                     "⛲"
CONST  EMOTE_MOYAI   =                        "🗿"
CONST  EMOTE_AUTOMATED_TELLER_MACHINE   =     "🏧"
CONST  EMOTE_BELL   =                         "🔔"
CONST  EMOTE_BROOM   =                        "🧹"
CONST  EMOTE_BASKET   =                       "🧺"
CONST  EMOTE_JACK_O_LANTERN   =               "🎃"
CONST  EMOTE_WRAPPED_PRESENT   =              "🎁"
CONST  EMOTE_PARTY_POPPER   =                 "🎉"
CONST  EMOTE_CONFETTI_BALL   =                "🎊"
CONST  EMOTE_SHOWER   =                       "🚿"
CONST  EMOTE_STETHOSCOPE   =                  "🩺"
CONST  EMOTE_ABACUS   =                       "🧮"
CONST  EMOTE_MICROSCOPE   =                   "🔬"
CONST  EMOTE_TELESCOPE   =                    "🔭"
CONST  EMOTE_SCALES   =                       "⚖️"
CONST  EMOTE_ALEMBIC   =                      "⚗️"
CONST  EMOTE_STAFF_OF_AESCULAPIUS   =         "⚕️"
CONST  EMOTE_STAFF_OF_HERMES   =              "⚚"
CONST  EMOTE_TOOLBOX   =                      "🧰"
CONST  EMOTE_BRICK   =                        "🧱"
CONST  EMOTE_PINE_DECORATION   =              "🎍"
CONST  EMOTE_COFFIN   =                       "⚰️"
CONST  EMOTE_FUNERAL_URN   =                  "⚱️"
CONST  EMOTE_ANCHOR   =                       "⚓"
CONST  EMOTE_FIRE_EXTINGUISHER   =            "🧯"
CONST  EMOTE_DIYA_LAMP   =                    "🪔"
CONST  EMOTE_BANJO   =                        "🪕"
CONST  EMOTE_PACKAGE   =                      "📦"
CONST  EMOTE_POSTAL_HORN   =                  "📯"
CONST  EMOTE_TELEVISION   =                   "📺"
CONST  EMOTE_RADIO   =                        "📻"
CONST  EMOTE_FILM_PROJECTOR   =               "📽️"
CONST  EMOTE_PORTABLE_STEREO   =              "📾"
CONST  EMOTE_WHITE_SQUARE_BUTTON   =          "🔳"
CONST  EMOTE_BLACK_SQUARE_BUTTON   =          "🔲"
CONST  EMOTE_FRAME_WITH_PICTURE   =           "🖼️"
CONST  EMOTE_FRAME_WITH_TILES   =             "🖽"
CONST  EMOTE_OIL_DRUM   =                     "🛢️"
CONST  EMOTE_BICYCLE   =                      "🚲"
CONST  EMOTE_SCOOTER   =                      "🛴"
CONST  EMOTE_SKATEBOARD   =                   "🛹"
CONST  EMOTE_BUS_STOP   =                     "🚏"
CONST  EMOTE_STUDIO_MICROPHONE   =            "🎙️"
CONST  EMOTE_MICROPHONE   =                   "🎤"
CONST  EMOTE_PERSONAL_COMPUTER   =            "💻"
CONST  EMOTE_ELECTRIC_PLUG   =                "🔌"
CONST  EMOTE_BATTERY   =                      "🔋"
CONST  EMOTE_JOYSTICK   =                     "🕹️"
CONST  EMOTE_SHOPPING_TROLLEY   =             "🛒"
CONST  EMOTE_BED   =                          "🛌"
CONST  EMOTE_BARBER_POLE   =                  "💈"
CONST  EMOTE_FUEL_PUMP   =                    "⛽"
CONST  EMOTE_ELECTRIC_LIGHT_BULB  =           "💡"

// Group Time Keepers
CONST  EMOTE_HOURGLASS  =                     "⌛"
CONST  EMOTE_HOURGLASS_WITH_FLOWING_SAND  =   "⏳"
CONST  EMOTE_CALENDAR   =                     "📅"
CONST  EMOTE_TEAR_OFF_CALENDAR   =            "📆"
CONST  EMOTE_ALARM_CLOCK   =                  "⏰"

// Group Nature 

CONST  EMOTE_HIBISCUS   =                     "🌺"
CONST  EMOTE_CHERRY_BLOSSOM   =               "🌸"
CONST  EMOTE_TULIP   =                        "🌷"
CONST  EMOTE_ROSE   =                         "🌹"
CONST  EMOTE_WHITE_FLOWER   =                 "💮"
CONST  EMOTE_MAPLE_LEAF   =                   "🍁"
CONST  EMOTE_FALLEN_LEAF   =                  "🍂"
CONST  EMOTE_LEAF_FLUTTERING_IN_WIND   =      "🍃"
CONST  EMOTE_EAR_OF_MAIZE   =                 "🌽"
CONST  EMOTE_EAR_OF_RICE   =                  "🌾"
CONST  EMOTE_HERB   =                         "🌿"
CONST  EMOTE_SEEDLING   =                     "🌱"
CONST  EMOTE_CHESTNUT   =                     "🌰"
CONST  EMOTE_EVERGREEN_TREE   =               "🌲"
CONST  EMOTE_DECIDUOUS_TREE   =               "🌳"
CONST  EMOTE_PALM_TREE   =                    "🌴"
CONST  EMOTE_CACTUS   =                       "🌵"
CONST  EMOTE_CHRISTMAS_TREE   =               "🎄"
CONST  EMOTE_ROSETTE   =                      "🏵️"
CONST  EMOTE_BLACK_ROSETTE   =                "🏶"

// Group Animals

CONST  EMOTE_UNICORN_FACE  =                  "🦄"
CONST  EMOTE_EAGLE  =                         "🦅"
CONST  EMOTE_FOX_FACE  =                      "🦊"
CONST  EMOTE_WHALE   =                        "🐋"
CONST  EMOTE_OCTOPUS   =                      "🐙"
CONST  EMOTE_FISH   =                         "🐟"
CONST  EMOTE_DOLPHIN   =                      "🐬"
CONST  EMOTE_SPOUTING_WHALE   =               "🐳"
CONST  EMOTE_TURTLE   =                       "🐢"
CONST  EMOTE_ELEPHANT   =                     "🐘"
CONST  EMOTE_DOG   =                          "🐕"
CONST  EMOTE_LION_FACE   =                    "🦁"
CONST  EMOTE_SNAKE   =                        "🐍"
CONST  EMOTE_SNAIL   =                        "🐌"
CONST  EMOTE_BAT   =                          "🦇"
CONST  EMOTE_PEACOCK   =                      "🦚"
CONST  EMOTE_RAT   =                          "🐀"
CONST  EMOTE_MOUSE   =                        "🐁"
CONST  EMOTE_OX   =                           "🐂"
CONST  EMOTE_WATER_BUFFALO   =                "🐃"
CONST  EMOTE_COW   =                          "🐄"
CONST  EMOTE_TIGER   =                        "🐅"
CONST  EMOTE_LEOPARD   =                      "🐆"
CONST  EMOTE_RABBIT   =                       "🐇"
CONST  EMOTE_CAT   =                          "🐈"
CONST  EMOTE_CROCODILE   =                    "🐊"
CONST  EMOTE_HORSE   =                        "🐎"
CONST  EMOTE_RAM   =                          "🐏"
CONST  EMOTE_GOAT   =                         "🐐"
CONST  EMOTE_SHEEP   =                        "🐑"
CONST  EMOTE_MONKEY   =                       "🐒"
CONST  EMOTE_ROOSTER   =                      "🐓"
CONST  EMOTE_CHICKEN   =                      "🐔"
CONST  EMOTE_DOG   =                          "🐕"
CONST  EMOTE_PIG   =                          "🐖"
CONST  EMOTE_BOAR   =                         "🐗"
CONST  EMOTE_ELEPHANT   =                     "🐘"
CONST  EMOTE_OCTOPUS   =                      "🐙"
CONST  EMOTE_FISH   =                         "🐟"
CONST  EMOTE_TROPICAL_FISH   =                "🐠"
CONST  EMOTE_BLOWFISH   =                     "🐡"
CONST  EMOTE_TURTLE   =                       "🐢"
CONST  EMOTE_HATCHING_CHICK   =               "🐣"
CONST  EMOTE_BABY_CHICK   =                   "🐤"
CONST  EMOTE_FRONT_FACING_BABY_CHICK   =      "🐥"
CONST  EMOTE_BIRD   =                         "🐦"
CONST  EMOTE_PENGUIN   =                      "🐧"
CONST  EMOTE_KOALA   =                        "🐨"
CONST  EMOTE_POODLE   =                       "🐩"
CONST  EMOTE_DROMEDARY_CAMEL   =              "🐪"
CONST  EMOTE_BACTRIAN_CAMEL   =               "🐫"
CONST  EMOTE_DOLPHIN   =                      "🐬"
CONST  EMOTE_SLOTH   =                        "🦥"
CONST  EMOTE_OTTER   =                        "🦦"
CONST  EMOTE_ORANGUTAN   =                    "🦧"
CONST  EMOTE_SKUNK   =                        "🦨"
CONST  EMOTE_FLAMINGO   =                     "🦩"
CONST  EMOTE_OYSTER   =                       "🦪"
CONST  EMOTE_BADGER   =                       "🦡"
CONST  EMOTE_SWAN   =                         "🦢"
CONST  EMOTE_RACCOON   =                      "🦝"
CONST  EMOTE_LOBSTER   =                      "🦞"
CONST  EMOTE_KANGAROO   =                     "🦘"
CONST  EMOTE_LLAMA   =                        "🦙"
CONST  EMOTE_PEACOCK   =                      "🦚"
CONST  EMOTE_HIPPOPOTAMUS   =                 "🦛"
CONST  EMOTE_PARROT  =                        "🦜"
CONST  EMOTE_HEDGEHOG   =                     "🦔"
CONST  EMOTE_DEER   =                         "🦌"
CONST  EMOTE_GORILLA   =                      "🦍"
CONST  EMOTE_LIZARD   =                       "🦎"
CONST  EMOTE_RHINOCEROS   =                   "🦏"
CONST  EMOTE_SHRIMP   =                       "🦐"
CONST  EMOTE_SQUID   =                        "🦑"
CONST  EMOTE_EAGLE   =                        "🦅"
CONST  EMOTE_DUCK   =                         "🦆"
CONST  EMOTE_BAT   =                          "🦇"
CONST  EMOTE_SHARK   =                        "🦈"
CONST  EMOTE_OWL   =                          "🦉"
CONST  EMOTE_CRAB   =                         "🦀"
CONST  EMOTE_SCORPION   =                     "🦂"
CONST  EMOTE_TURKEY   =                       "🦃"

// Group Insect

CONST  EMOTE_BUTTERFLY  =                     "🦋"
CONST  EMOTE_MOSQUITO  =                      "🦟"
CONST  EMOTE_BUG   =                          "🐛"
CONST  EMOTE_HONEYBEE   =                     "🐝"
CONST  EMOTE_LADY_BEETLE   =                  "🐞"
CONST  EMOTE_ANT   =                          "🐜"
CONST  EMOTE_SPIDER   =                       "🕷️"
CONST  EMOTE_SCORPION   =                     "🦂"
CONST  EMOTE_CRICKET   =                      "🦗"

// Group Entities

CONST  EMOTE_MAGE   =                         "🧙"
CONST  EMOTE_FAIRY   =                        "🧚"
CONST  EMOTE_VAMPIRE   =                      "🧛"
CONST  EMOTE_MERPERSON   =                    "🧜"
CONST  EMOTE_ELF   =                          "🧝"
CONST  EMOTE_GENIE   =                        "🧞"
CONST  EMOTE_ZOMBIE   =                       "🧟"
CONST  EMOTE_SUPERHERO   =                    "🦸"
CONST  EMOTE_SUPERVILLAIN   =                 "🦹"
CONST  EMOTE_GHOST   =                        "👻"
CONST  EMOTE_IMP   =                          "👿"
CONST  EMOTE_BABY_ANGEL   =                   "👼"
CONST  EMOTE_EXTRATERRESTRIAL_ALIEN   =       "👽"
CONST  EMOTE_ALIEN_MONSTER   =                "👾"
CONST  EMOTE_DRAGON   =                       "🐉"
CONST  EMOTE_DRAGON_FACE   =                  "🐲"
CONST  EMOTE_JAPANESE_GOBLIN   =              "👺"
CONST  EMOTE_JAPANESE_OGRE   =                "👹"
CONST  EMOTE_ROBOT_FACE  =                    "🤖"

// Group People

CONST  EMOTE_CLOWN_FACE  =                    "🤡"
CONST  EMOTE_PRINCE   =                       "🤴"
CONST  EMOTE_PRINCESS   =                     "👸"
CONST  EMOTE_BABY   =                         "👶"
CONST  EMOTE_OLDER_WOMAN   =                  "👵"
CONST  EMOTE_OLDER_MAN   =                    "👴"
CONST  EMOTE_BRIDE_WITH_VEIL   =              "👰"
CONST  EMOTE_RUNNER  =                        "🏃"
CONST  EMOTE_PEDESTRIAN   =                   "🚶"
CONST  EMOTE_MAN_DANCING   =                  "🕺"
CONST  EMOTE_DANCER   =                       "💃"
CONST  EMOTE_GUARDSMAN   =                    "💂"
CONST  EMOTE_CONSTRUCTION_WORKER   =          "👷"
CONST  EMOTE_MAN_WITH_TURBAN   =              "👳"
CONST  EMOTE_WOMAN_WITH_BUNNY_EARS   =        "👯"
CONST  EMOTE_POLICE_OFFICER   =               "👮"
CONST  EMOTE_TWO_WOMEN_HOLDING_HANDS   =      "👭"
CONST  EMOTE_TWO_MEN_HOLDING_HANDS   =        "👬"
CONST  EMOTE_MAN_AND_WOMAN_HOLDING_HANDS   =  "👫"
CONST  EMOTE_FAMILY   =                       "👪"
CONST  EMOTE_WOMAN   =                        "👩"
CONST  EMOTE_MAN   =                          "👨"
CONST  EMOTE_GIRL   =                         "👧"
CONST  EMOTE_BOY   =                          "👦"
CONST  EMOTE_BEARDED_PERSON   =               "🧔"
CONST  EMOTE_OLDER_ADULT   =                  "🧓"
CONST  EMOTE_CHILD   =                        "🧒"
CONST  EMOTE_ADULT   =                        "🧑"
CONST  EMOTE_PREGNANT_WOMAN   =               "🤰"
CONST  EMOTE_PERSON_WITH_HEADSCARF   =        "🧕"
CONST  EMOTE_MOTHER_CHRISTMAS   =             "🤶"
CONST  EMOTE_FATHER_CHRISTMAS   =             "🎅"

// Group Occupations

CONST  EMOTE_FISHING_POLE_AND_FISH   =        "🎣"
CONST  EMOTE_PERFORMING_ARTS   =              "🎭"

// Group Bags

CONST  EMOTE_MONEY_BAG  =                     "💰"
CONST  EMOTE_HANDBAG  =                       "👜"
CONST  EMOTE_SCHOOL_SATCHEL   =               "🎒"
CONST  EMOTE_BRIEFCASE   =                    "💼"
CONST  EMOTE_PURSE   =                        "👛"
CONST  EMOTE_POUCH   =                        "👝"


// Group Elements & Weather

CONST  EMOTE_FIRE  =                          "🔥"
CONST  EMOTE_DROPLET  =                       "💧"
CONST  EMOTE_ICE_CUBE  =                      "🧊"
CONST  EMOTE_SNOWFLAKE   =                    "❄️"
CONST  EMOTE_CLOUD_WITH_SNOW   =              "🌨️"
CONST  EMOTE_CLOUD_WITH_LIGHTNING   =         "🌩️"
CONST  EMOTE_WHITE_SUN_BEHIND_CLOUD   =       "⛅"
CONST  EMOTE_TORNADO   =                      "🌪️"
CONST  EMOTE_CLOUD_WITH_RAIN   =              "🌧️"
CONST  EMOTE_FOG   =                          "🌫️"
CONST  EMOTE_WIND_BLOWING_FACE   =            "🌬️"
CONST  EMOTE_HIGH_BRIGHTNESS_SYMBOL   =       "🔆"
CONST  EMOTE_LOW_BRIGHTNESS_SYMBOL   =        "🔅"

// Group Hand Gestures

CONST  EMOTE_HANDSHAKE  =                     "🤝"
CONST  EMOTE_WAVING_HAND_SIGN   =             "👋"
CONST  EMOTE_OK_HAND_SIGN   =                 "👌"
CONST  EMOTE_CLAPPING_HANDS_SIGN   =          "👏"
CONST  EMOTE_FOLDED_HANDS   =                 "🙏"
CONST  EMOTE_HANDS_IN_CELEBRATION   =         "🙌"
CONST  EMOTE_MIDDLE_FINGER   =                "🖕"
CONST  EMOTE_SPOCK   =                        "🖖"
CONST  EMOTE_FINGERS_CROSSED   =              "🤞"
CONST  EMOTE_RAISED_FIST   =                  "✊"
CONST  EMOTE_RAISED_HAND   =                  "✋"
CONST  EMOTE_FISTED_HAND_SIGN   =             "👊"
CONST  EMOTE_OK_HAND_SIGN   =                 "👌"
CONST  EMOTE_CLAPPING_HANDS_SIGN   =          "👏"
CONST  EMOTE_THUMBS_UP_SIGN   =               "👍"
CONST  EMOTE_THUMBS_DOWN_SIGN   =             "👎"
CONST  EMOTE_RAISING_HANDS_IN_CELEBRATION   = "🙌"
CONST  EMOTE_PERSON_WITH_FOLDED_HANDS   =     "🙏"
CONST  EMOTE_WRITING_HAND   =                 "✍"

// Group Communication

CONST  EMOTE_LEFT_SPEECH_BUBBLE  =            "🗨️"
CONST  EMOTE_RIGHT_SPEECH_BUBBLE  =           "🗩"
CONST  EMOTE_TWO_SPEECH_BUBBLES  =            "🗪"
CONST  EMOTE_THREE_SPEECH_BUBBLES  =          "🗫"
CONST  EMOTE_LEFT_THOUGHT_BUBBLE  =           "🗬"
CONST  EMOTE_RIGHT_THOUGHT_BUBBLE  =          "🗭"
CONST  EMOTE_LEFT_ANGER_BUBBLE  =             "🗮"
CONST  EMOTE_RIGHT_ANGER_BUBBLE  =            "🗯️"
CONST  EMOTE_MOOD_BUBBLE  =                   "🗰"
CONST  EMOTE_LIGHTNING_MOOD_BUBBLE  =         "🗱"
CONST  EMOTE_LIGHTNING_MOOD  =                "🗲"
CONST  EMOTE_SPEAKING_HEAD  =                 "🗣️"

// Group Messaging Symbols 

CONST  EMOTE_MOBILE_PHONE   =                 "📱"
CONST  EMOTE_MOBILE_PHONE_WITH_ARROW_LEFT   = "📲"
CONST  EMOTE_VIBRATION_MODE   =               "📳"
CONST  EMOTE_MOBILE_PHONE_OFF   =             "📴"
CONST  EMOTE_OUTBOX_TRAY   =                  "📤"
CONST  EMOTE_INBOX_TRAY   =                   "📥"
CONST  EMOTE_CLOSED_MAILBOX_RAISED_FLAG   =   "📫"
CONST  EMOTE_OPEN_MAILBOX_LOWERED_FLAG   =    "📭"
CONST  EMOTE_CHEERING_MEGAPHONE   =           "📣"
CONST  EMOTE_PUBLIC_ADDRESS_LOUDSPEAKER   =   "📢"

// Group Space 

CONST  EMOTE_EARTH_GLOBE   =                  "🌍"
CONST  EMOTE_MILKY_WAY   =                    "🌌"
CONST  EMOTE_NEW_MOON   =                     "🌑"
CONST  EMOTE_CRESCENT_MOON   =                "🌒"
CONST  EMOTE_FIRST_QUARTER_MOON     =         "🌓"
CONST  EMOTE_SECOND_QUARTER_MOON   =          "🌔"
CONST  EMOTE_FULL_MOON   =                    "🌕"
CONST  EMOTE_THIRD_QUARTER   =                "🌖"
CONST  EMOTE_FOURTH_QUARTER_MOON   =          "🌗"
CONST  EMOTE_LAST_QUARTER_MOON    =           "🌘"
CONST  EMOTE_CRESCENT_MOON_EMPTY   =          "🌙"
CONST  EMOTE_SHOOTING_STAR   =                "🌠"
CONST  EMOTE_GLOWING_STAR   =                 "🌟"
CONST  EMOTE_WHITE_MEDIUM_STAR   =            "⭐"
CONST  EMOTE_RINGED_PLANET   =                "🪐"
CONST  EMOTE_SATELLITE   =                    "🛰️"

// Group Musical 

CONST  EMOTE_MUSICAL_SCORE  =                 "🎼"
CONST  EMOTE_MUSICAL_NOTE   =                 "🎵"
CONST  EMOTE_MULTIPLE_MUSICAL_NOTES   =       "🎶"
CONST  EMOTE_MUSICAL_SYMBOL_G_CLEF   =        "𝄞"
CONST  EMOTE_MUSICAL_FIVE_LINE_STAFF   =      "𝄚"
CONST  EMOTE_MUSICAL_LEFT_REPEAT_SIGN   =     "𝄆"
CONST  EMOTE_MUSICAL_RIGHT_REPEAT_SIGN   =    "𝄇"
CONST  EMOTE_MUSICAL_FINAL_BARLINE   =        "𝄂"
CONST  EMOTE_MUSICAL_REVERS_FINAL_BARLINE   = "𝄃"
CONST  EMOTE_QUARTER_NOTE   =                 "♩"
CONST  EMOTE_EIGHTH_NOTE   =                  "♪"
CONST  EMOTE_BEAMED_EIGHTH_NOTES   =          "♫"
CONST  EMOTE_BEAMED_SIXTEENT_NOTES   =        "♬"

// Group Currency 

CONST  EMOTE_CURRENCY_EXCHANGE   =            "💱"
CONST  EMOTE_HEAVY_DOLLAR_SIGN   =            "💲"
CONST  EMOTE_CREDIT_CARD   =                  "💳"
CONST  EMOTE_BANKNOTE_WITH_YEN_SIGN   =       "💴"
CONST  EMOTE_BANKNOTE_WITH_DOLLAR_SIGN   =    "💵"
CONST  EMOTE_BANKNOTE_WITH_EURO_SIGN   =      "💶"
CONST  EMOTE_BANKNOTE_WITH_POUND_SIGN   =     "💷"
CONST  EMOTE_MONEY_WITH_WINGS   =             "💸"
CONST  EMOTE_K_Symbol   =                     "₭"
CONST  EMOTE_B_Symbol   =                     "฿"

// Group Medical

CONST  EMOTE_PILL   =                         "💊"
CONST  EMOTE_SYRINGE   =                      "💉"
CONST  EMOTE_ADHESIVE_BANDAGE   =             "🩹"
CONST  EMOTE_DNA_DOUBLE_HELIX   =             "🧬"
CONST  EMOTE_MICROBE   =                      "🦠"
CONST  EMOTE_LAB_COAT   =                     "🥼"

// Group Office 

CONST  EMOTE_POSTBOX   =                      "📮"
CONST  EMOTE_LOVE_LETTER   =                  "💌"
CONST  EMOTE_BOOKMARK_TABS   =                "📑"
CONST  EMOTE_NOTEBOOK   =                     "📓"
CONST  EMOTE_NOTEBOOK_WITH_COVER   =          "📔"
CONST  EMOTE_MEMO   =                         "📝"
CONST  EMOTE_CLOSED_BOOK   =                  "📕"
CONST  EMOTE_GREEN_BOOK   =                   "📗"
CONST  EMOTE_BLUE_BOOK   =                    "📘"
CONST  EMOTE_ORANGE_BOOK   =                  "📙"
CONST  EMOTE_OPEN_BOOK   =                    "📖"
CONST  EMOTE_BOOKS   =                        "📚"
CONST  EMOTE_CLIPBOARD   =                    "📋"
CONST  EMOTE_PAPERCLIP   =                    "📎"
CONST  EMOTE_ROUND_PUSHPIN   =                "📍"
CONST  EMOTE_PUSHPIN   =                      "📌"
CONST  EMOTE_STRAIGHT_RULER   =               "📏"
CONST  EMOTE_TRIANGULAR_RULER   =             "📐"
CONST  EMOTE_TELEPHONE_RECEIVER   =           "📞"
CONST  EMOTE_SCISSORS   =                     "✂️"
CONST  EMOTE_NEWSPAPER   =                    "📰"
CONST  EMOTE_ROLLED_UP_NEWSPAPER   =          "🗞️"
CONST  EMOTE_PAGE_WITH_CIRCLED_TEXT   =       "🗟"
CONST  EMOTE_CARD_INDEX_DIVIDERS   =          "🗂"
CONST  EMOTE_CARD_FILE_BOX   =                "🗃"
CONST  EMOTE_FILE_CABINET   =                 "🗄"
CONST  EMOTE_BOOKMARK   =                     "🔖"
CONST  EMOTE_CARD_INDEX   =                   "📇"
CONST  EMOTE_NAME_BADGE   =                   "📛"
CONST  EMOTE_CHART_WITH_UPWARDS_TREND   =     "📈"
CONST  EMOTE_CHART_WITH_DOWNWARDS_TREND   =   "📉"
CONST  EMOTE_BAR_CHART   =                    "📊"
CONST  EMOTE_LOWER_RIGHT_PENCIL   =           "✎"
CONST  EMOTE_LABEL   =                        "🏷"
CONST  EMOTE_WASTEBASKET   =                  "🗑"

// Group Instruments

CONST  EMOTE_SAXOPHONE   =                    "🎷"
CONST  EMOTE_GUITAR   =                       "🎸"
CONST  EMOTE_MUSICAL_KEYBOARD   =             "🎹"
CONST  EMOTE_TRUMPET   =                      "🎺"
CONST  EMOTE_VIOLIN   =                       "🎻"
CONST  EMOTE_DRUM_WITH_DRUMSTICKS   =         "🥁"

// Group Transportation & Vehicles

CONST  EMOTE_MOTOR_BOAT   =                   "🛥"
CONST  EMOTE_UP_MILITARY_AIRPLANE   =         "🛦"
CONST  EMOTE_UP_AIRPLANE   =                  "🛧"
CONST  EMOTE_PASSENGER_SHIP   =               "🛳"
CONST  EMOTE_DIESEL_LOCOMOTIVE   =            "🛲"
CONST  EMOTE_ONCOMING_FIRE_ENGINE   =         "🛱"
CONST  EMOTE_MOTOR_SCOOTER   =                "🛵"
CONST  EMOTE_CANOE   =                        "🛶"
CONST  EMOTE_TAXI   =                         "🚕"
CONST  EMOTE_AUTOMOBILE   =                   "🚗"
CONST  EMOTE_POLICE_CAR   =                   "🚓"
CONST  EMOTE_TRACTOR   =                      "🚜"
CONST  EMOTE_FIRE_ENGINE   =                  "🚒"
CONST  EMOTE_AMBULANCE   =                    "🚑"
CONST  EMOTE_DELIVERY_TRUCK   =               "🚚"
CONST  EMOTE_ARTICULATED_LORRY   =            "🚛"
CONST  EMOTE_BUS   =                          "🚌"
CONST  EMOTE_TROLLEYBUS   =                   "🚎"
CONST  EMOTE_MINIBUS   =                      "🚐"
CONST  EMOTE_STATION   =                      "🚉"
CONST  EMOTE_TRAIN   =                        "🚆"
CONST  EMOTE_HIGH_SPEED_TRAIN   =             "🚄"
CONST  EMOTE_HIGH_SPEED_BULLET_TRAIN   =      "🚅"
CONST  EMOTE_MONORAIL   =                     "🚝"
CONST  EMOTE_RAILWAY_CAR   =                  "🚃"
CONST  EMOTE_METRO   =                        "🚇"
CONST  EMOTE_LIGHT_RAIL   =                   "🚈"
CONST  EMOTE_TRAM   =                         "🚊"
CONST  EMOTE_TRAM_CAR   =                     "🚋"
CONST  EMOTE_MOUNTAIN_RAILWAY   =             "🚞"
CONST  EMOTE_SUSPENSION_RAILWAY   =           "🚟"
CONST  EMOTE_MOUNTAIN_CABLEWAY   =            "🚠"
CONST  EMOTE_AERIAL_TRAMWAY   =               "🚡"
CONST  EMOTE_SHIP   =                         "🚢"
CONST  EMOTE_ROWBOAT   =                      "🚣"
CONST  EMOTE_SPEEDBOAT   =                    "🚤"
CONST  EMOTE_FERRY   =                        "⛴"
CONST  EMOTE_SAILBOAT   =                     "⛵"
CONST  EMOTE_ROCKET   =                       "🚀"
CONST  EMOTE_HELICOPTER   =                   "🚁"
CONST  EMOTE_STEAM_LOCOMOTIVE  =              "🚂"
CONST  EMOTE_FLYING_SAUCER  =                 "🛸"

// Group Road & Other Signs

CONST  EMOTE_OCTAGONAL_SIGN   =               "🛑"
CONST  EMOTE_NO_ENTRY   =                     "⛔"
CONST  EMOTE_NO_ENTRY_SIGN   =                "🚫"
CONST  EMOTE_POLICE_CARS_REVOLVING_LIGHT   =  "🚨"
CONST  EMOTE_NO_SMOKING_SYMBOL   =            "🚭"
CONST  EMOTE_CONSTRUCTION_SIGN   =            "🚧"
CONST  EMOTE_VERTICAL_TRAFFIC_LIGHT   =       "🚦"
CONST  EMOTE_HORIZONTAL_TRAFFIC_LIGHT   =     "🚥"
CONST  EMOTE_SPEAKER_THREE_SOUND_WAVES   =    "🔊"
CONST  EMOTE_SPEAKER_ONE_SOUND_WAVE   =       "🔉"
CONST  EMOTE_SPEAKER   =                      "🔈"

// Group Special Signs

CONST  EMOTE_SKULL_AND_CROSSBONES   =         "☠"
CONST  EMOTE_RADIOACTIVE_SIGN   =             "☢"
CONST  EMOTE_BIOHAZARD_SIGN   =               "☣"
CONST  EMOTE_ANKH   =                         "☥"
CONST  EMOTE_YIN_YANG   =                     "☯"
CONST  EMOTE_FEMALE_SIGN   =                  "♀"
CONST  EMOTE_MALE_SIGN   =                    "♂"

// Group Sports

CONST  EMOTE_BICYCLIST   =                    "🚴"
CONST  EMOTE_WRESTLERS   =                    "🤼"
CONST  EMOTE_BADMINTON_RACQUET   =            "🏸"
CONST  EMOTE_TABLE_TENNIS_PADDLE_AND_BALL   = "🏓"
CONST  EMOTE_ICE_HOCKEY_STICK_AND_PUCK   =    "🏒"
CONST  EMOTE_FIELD_HOCKEY_STICK_AND_BALL   =  "🏑"
CONST  EMOTE_VOLLEYBALL   =                   "🏐"
CONST  EMOTE_CRICKET_BAT_AND_BALL   =         "🏏"
CONST  EMOTE_RACING_CAR   =                   "🏎"
CONST  EMOTE_RACING_MOTORCYCLE   =            "🏍"
CONST  EMOTE_GOLFER   =                       "🏌"
CONST  EMOTE_WEIGHT_LIFTER   =                "🏋"
CONST  EMOTE_SWIMMER   =                      "🏊"
CONST  EMOTE_RUGBY_FOOTBALL   =               "🏉"
CONST  EMOTE_AMERICAN_FOOTBALL   =            "🏈"
CONST  EMOTE_HORSE_RACING   =                 "🏇"
CONST  EMOTE_SURFER   =                       "🏄"
CONST  EMOTE_SNOWBOARDER   =                  "🏂"
CONST  EMOTE_TENNIS_RACQUET_AND_BALL   =      "🎾"
CONST  EMOTE_SKI_AND_SKI_BOOT   =             "🎿"
CONST  EMOTE_BASKETBALL_AND_HOOP   =          "🏀"
CONST  EMOTE_GOAL_NET   =                     "🥅"
CONST  EMOTE_MARTIAL_ARTS_UNIFORM   =         "🥋"
CONST  EMOTE_BOXING_GLOVE   =                 "🥊"

// Group Clothing

CONST  EMOTE_GOGGLES   =                      "🥽"
CONST  EMOTE_SARI   =                         "🥻"
CONST  EMOTE_BILLED_CAP   =                   "🧢"
CONST  EMOTE_SCARF   =                        "🧣"
CONST  EMOTE_GLOVES   =                       "🧤"
CONST  EMOTE_COAT   =                         "🧥"
CONST  EMOTE_SOCKS   =                        "🧦"
CONST  EMOTE_BALLET_SHOES   =                 "🩰"
CONST  EMOTE_ONE_PIECE_SWIMSUIT   =           "🩱"
CONST  EMOTE_BRIEFS   =                       "🩲"
CONST  EMOTE_SHORTS   =                       "🩳"
CONST  EMOTE_RUNNING_SHIRT_WITH_SASH   =      "🎽"
CONST  EMOTE_WOMANS_HAT   =                   "👒"
CONST  EMOTE_EYEGLASSES   =                   "👓"
CONST  EMOTE_NECKTIE   =                      "👔"
CONST  EMOTE_T_SHIRT   =                      "👕"
CONST  EMOTE_JEANS   =                        "👖"
CONST  EMOTE_DRESS   =                        "👗"
CONST  EMOTE_KIMONO   =                       "👘"
CONST  EMOTE_BIKINI   =                       "👙"
CONST  EMOTE_WOMANS_CLOTHES   =               "👚"
CONST  EMOTE_MANS_SHOE   =                    "👞"
CONST  EMOTE_ATHLETIC_SHOE   =                "👟"
CONST  EMOTE_HIGH_HEELED_SHOE   =             "👠"
CONST  EMOTE_WOMANS_SANDAL   =                "👡"
CONST  EMOTE_WOMANS_BOOTS   =                 "👢"

// Group Map Symbols

CONST  EMOTE_HOT_SPRINGS   =                  "♨"
CONST  EMOTE_MOTORWAY   =                     "🛣"
CONST  EMOTE_RAILWAY_TRACK   =                "🛤"
CONST  EMOTE_CASTLE   =                       "⛫"
CONST  EMOTE_HISTORIC_SITE   =                "⛬"
CONST  EMOTE_HEADSTONE_GRAVEYARD_SYMBOL   =   "⛼"
CONST  EMOTE_JAPANESE_BANK_SYMBOL   =         "⛻"
CONST  EMOTE_MAP_SYMBOL_FOR_LIGHTHOUSE   =    "⛯"
CONST  EMOTE_HOLLOW_QUILT_SQUARE_   =         "🙨"
CONST  EMOTE_HOLLOW_QUILT_SQUARE_BLACK   =    "🙩"

// Group Arrows

CONST ARROW_UP = "⮝"
CONST ARROW_DOWN = "⮟"
CONST ARROW_LEFT = "⮜"
CONST ARROW_RIGHT = "⮞"


// Group Misc

CONST  EMOTE_ETERNITY_SIGN  =                 "֎"
CONST  EMOTE_HAMMER_AND_WRENCH  =             "🛠"
CONST  EMOTE_SQUARE_TARGET  =                 "🞖"
CONST  EMOTE_PAW_PRINTS   =                   "🐾"
CONST  EMOTE_FOOTPRINTS   =                   "👣"
CONST  EMOTE_SATELLITE_ANTENNA   =            "📡"
CONST  EMOTE_DOVE_OF_PEACE   =                "🕊"
CONST  EMOTE_FLEUR_DE_LIS   =                 "⚜"
CONST  EMOTE_ATOM_SYMBOL   =                  "⚛"
CONST  EMOTE_WAVING_BLACK_FLAG   =            "🏴"
CONST  EMOTE_CHEQUERED_FLAG   =               "🏁"
CONST  EMOTE_CUP_ON_BLACK_SQUARE   =          "⛾"
CONST  EMOTE_OBJECT_REPLACEMENT   =           "￼"
CONST  EMOTE_REPLACEMENT_CHARACTER   =        "�"

// Group Specials

CONST  EMOTE_PLAYING_CARD_BLACK_JOKER   =     "🃏"
CONST  EMOTE_CYCLONE  =                       "🌀"
CONST  EMOTE_TRIDENT_EMBLEM  =                "🔱"
CONST  EMOTE_TENT   =                         "⛺"
CONST  EMOTE_CAMPING   =                      "🏕"
CONST  EMOTE_RAINBOW   =                      "🌈"
CONST  EMOTE_SNOWMAN_WITHOUT_SNOW   =         "⛄"
CONST  EMOTE_SAUROPOD   =                     "🦕"
CONST  EMOTE_T_REX   =                        "🦖"
CONST  EMOTE_FIREWORKS   =                    "🎆"
CONST  EMOTE_FIREWORK_SPARKLER   =            "🎇"
CONST  EMOTE_SPARKLES   =                     "✨"
CONST  EMOTE_WORLD_MAP   =                    "🗺"
CONST  EMOTE_REMINDER_RIBBON   =              "🎗"
CONST  EMOTE_CROSSED_SWORDS   =               "⚔"
CONST  EMOTE_LINK_SYMBOL   =                  "🔗"
CONST  EMOTE_OPEN_LOCK   =                    "🔓"
CONST  EMOTE_LOCK   =                         "🔒"
CONST  EMOTE_FILM_FRAMES   =                  "🎞"
CONST  EMOTE_SEE_NO_EVIL_MONKEY   =           "🙈"
CONST  EMOTE_HEAR_NO_EVIL_MONKEY   =          "🙉"
CONST  EMOTE_SPEAK_NO_EVIL_MONKEY   =         "🙊"
CONST  EMOTE_BUST_IN_SILHOUETTE   =           "👤"
CONST  EMOTE_BUSTS_IN_SILHOUETTE   =          "👥"
CONST  EMOTE_WHITE_HEAVY_CHECK_MARK   =       "✅"
CONST  EMOTE_CROSS_MARK   =                   "❌"
CONST  EMOTE_BLACK_QUESTION_MARK   =          "❓"
CONST  EMOTE_HEAVY_EXCLAMATION_MARK   =       "❗"
CONST  EMOTE_SQUARED_VS   =                   "🆚"

//Group Faces

CONST  EMOTE_FACE_WITH_HEAD_BANDAGE   =                                   "🤕"
CONST  EMOTE_THINKING_FACE   =                                            "🤔"
CONST  EMOTE_ZIPPER_MOUTH_FACE   =                                        "🤐"
CONST  EMOTE_MONEY_MOUTH_FACE   =                                         "🤑"
CONST  EMOTE_NAUSEATED_FACE   =                                           "🤢"
CONST  EMOTE_GRINNING_FACE_WITH_STAR_EYES   =                             "🤩"
CONST  EMOTE_ROLLING_ON_THE_FLOOR_LAUGHING   =                            "🤣"
CONST  EMOTE_DROOLING_FACE   =                                            "🤤"
CONST  EMOTE_SNEEZING_FACE   =                                            "🤧"
CONST  EMOTE_FACE_WITH_ONE_EYEBROW_RAISED   =                             "🤨"
CONST  EMOTE_GRINNING_FACE_WITH_ONE_LARGE_AND_ONE_SMALL_EYE   =           "🤪"
CONST  EMOTE_SERIOUS_FACE_WITH_SYMBOLS_COVERING_MOUTH   =                 "🤬"
CONST  EMOTE_SMILING_FACE_WITH_SMILING_EYES_AND_HAND_COVERING_MOUTH   =   "🤭"
CONST  EMOTE_FACE_WITH_OPEN_MOUTH_VOMITING   =                            "🤮"
CONST  EMOTE_SHOCKED_FACE_WITH_EXPLODING_HEAD   =                         "🤯"
CONST  EMOTE_SMILING_FACE_WITH_SMILING_EYES_AND_THREE_HEARTS   =          "🥰"
CONST  EMOTE_YAWNING_FACE   =                                             "🥱"
CONST  EMOTE_FACE_WITH_PARTY_HORN_AND_PARTY_HAT   =                       "🥳"
CONST  EMOTE_FACE_WITH_UNEVEN_EYES_AND_WAVY_MOUTH   =                     "🥴"
CONST  EMOTE_OVERHEATED_FACE   =                                          "🥵"
CONST  EMOTE_FREEZING_FACE   =                                            "🥶"
CONST  EMOTE_FACE_WITH_PLEADING_EYES   =                                  "🥺"
CONST  EMOTE_FACE_WITH_MONOCLE   =                                        "🧐"
CONST  EMOTE_GRINNING_FACE_WITH_SMILING_EYES   =                          "😁"
CONST  EMOTE_FACE_WITH_TEARS_OF_JOY   =                                   "😂"
CONST  EMOTE_SMILING_FACE_WITH_OPEN_MOUTH_AND_SMILING_EYES   =            "😄"
CONST  EMOTE_SMILING_FACE_WITH_OPEN_MOUTH_AND_COLD_SWEAT   =              "😅"
CONST  EMOTE_SMILING_FACE_WITH_HALO   =                                   "😇"
CONST  EMOTE_SMILING_FACE_WITH_HORNS   =                                  "😈"
CONST  EMOTE_WINKING_FACE   =                                             "😉"
CONST  EMOTE_SMILING_FACE_WITH_SMILING_EYES   =                           "😊"
CONST  EMOTE_FACE_SAVOURING_DELICIOUS_FOOD   =                            "😋"
CONST  EMOTE_RELIEVED_FACE   =                                            "😌"
CONST  EMOTE_SMILING_FACE_WITH_HEART_SHAPED_EYES   =                      "😍"
CONST  EMOTE_SMILING_FACE_WITH_SUNGLASSES   =                             "😎"
CONST  EMOTE_NEUTRAL_FACE   =                                             "😐"
CONST  EMOTE_UNAMUSED_FACE   =                                            "😒"
CONST  EMOTE_CONFOUNDED_FACE   =                                          "😖"
CONST  EMOTE_FACE_THROWING_A_KISS   =                                     "😘"
CONST  EMOTE_FACE_WITH_STUCK_OUT_TONGUE_AND_WINKING_EYE   =               "😜"
CONST  EMOTE_WORRIED_FACE   =                                             "😟"
CONST  EMOTE_DISAPPOINTED_FACE   =                                        "😞"
CONST  EMOTE_ANGRY_FACE   =                                               "😠"
CONST  EMOTE_POUTING_FACE   =                                             "😡"
CONST  EMOTE_CRYING_FACE   =                                              "😢"
CONST  EMOTE_FACE_WITH_LOOK_OF_TRIUMPH   =                                "😤"
CONST  EMOTE_ANGUISHED_FACE   =                                           "😧"
CONST  EMOTE_FEARFUL_FACE   =                                             "😨"
CONST  EMOTE_WEARY_FACE   =                                               "😩"
CONST  EMOTE_SLEEPY_FACE   =                                              "😪"
CONST  EMOTE_LOUDLY_CRYING_FACE   =                                       "😭"
CONST  EMOTE_FACE_WITH_OPEN_MOUTH_AND_COLD_SWEAT   =                      "😰"
CONST  EMOTE_FACE_SCREAMING_IN_FEAR   =                                   "😱"
CONST  EMOTE_ASTONISHED_FACE   =                                          "😲"
CONST  EMOTE_SLEEPING_FACE   =                                            "😴"
CONST  EMOTE_FLUSHED_FACE   =                                             "😳"
CONST  EMOTE_DIZZY_FACE   =                                               "😵"
CONST  EMOTE_FACE_WITHOUT_MOUTH   =                                       "😶"
CONST  EMOTE_FACE_WITH_MEDICAL_MASK   =                                   "😷"
CONST  EMOTE_FACE_WITH_ROLLING_EYES   =                                   "🙄"
CONST  EMOTE_GRINNING_CAT_FACE_WITH_SMILING_EYES   =                      "😸"
CONST  EMOTE_SMILING_CAT_FACE_WITH_HEART_SHAPED_EYES   =                  "😻"
CONST  EMOTE_CRYING_CAT_FACE   =                                          "😿"
CONST  EMOTE_CAT_FACE_WITH_WRY_SMILE   =                                  "😼"
CONST  EMOTE_POUTING_CAT_FACE   =                                         "😾"
